// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM2WdzazkEO2MY3qDZoCAhg3SjEVo1jrc',
    appId: '1:43965921184:web:f241e5554597e482e616c5',
    messagingSenderId: '43965921184',
    projectId: 'minimalchatapp-49134',
    authDomain: 'minimalchatapp-49134.firebaseapp.com',
    storageBucket: 'minimalchatapp-49134.appspot.com',
    measurementId: 'G-T0ZJ0C5VRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_xYIeaB0gNa53xgJgHv46ntJvMmUq0Y',
    appId: '1:43965921184:android:c57376d35fb19918e616c5',
    messagingSenderId: '43965921184',
    projectId: 'minimalchatapp-49134',
    storageBucket: 'minimalchatapp-49134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTgnrt7-sjbdbWaL-UgrhMUJHxMugqoLE',
    appId: '1:43965921184:ios:f89d1c7850306d03e616c5',
    messagingSenderId: '43965921184',
    projectId: 'minimalchatapp-49134',
    storageBucket: 'minimalchatapp-49134.appspot.com',
    iosClientId: '43965921184-vcmbvqhhpfe3o9cj2een49a53ml46bde.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTgnrt7-sjbdbWaL-UgrhMUJHxMugqoLE',
    appId: '1:43965921184:ios:f89d1c7850306d03e616c5',
    messagingSenderId: '43965921184',
    projectId: 'minimalchatapp-49134',
    storageBucket: 'minimalchatapp-49134.appspot.com',
    iosClientId: '43965921184-vcmbvqhhpfe3o9cj2een49a53ml46bde.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM2WdzazkEO2MY3qDZoCAhg3SjEVo1jrc',
    appId: '1:43965921184:web:7a7eb735813d2ea6e616c5',
    messagingSenderId: '43965921184',
    projectId: 'minimalchatapp-49134',
    authDomain: 'minimalchatapp-49134.firebaseapp.com',
    storageBucket: 'minimalchatapp-49134.appspot.com',
    measurementId: 'G-VDT21F2HT1',
  );
}
