// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmAX1hgdnO911Ya9oj1x3UMXYv9cRiek',
    appId: '1:470866763792:web:dc5eab4c2058b1ff26aa95',
    messagingSenderId: '470866763792',
    projectId: 'authyaksignin',
    authDomain: 'authyaksignin.firebaseapp.com',
    storageBucket: 'authyaksignin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLZls1SCfiiZmLWPkBr87T_39ISydtcs',
    appId: '1:470866763792:android:50e02e962fb14a2426aa95',
    messagingSenderId: '470866763792',
    projectId: 'authyaksignin',
    storageBucket: 'authyaksignin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqBcIgc2GwnqCoxC_aFaxo4IsewHPn4PU',
    appId: '1:470866763792:ios:4978cdf27771922526aa95',
    messagingSenderId: '470866763792',
    projectId: 'authyaksignin',
    storageBucket: 'authyaksignin.appspot.com',
    iosBundleId: 'com.example.loginauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqBcIgc2GwnqCoxC_aFaxo4IsewHPn4PU',
    appId: '1:470866763792:ios:4978cdf27771922526aa95',
    messagingSenderId: '470866763792',
    projectId: 'authyaksignin',
    storageBucket: 'authyaksignin.appspot.com',
    iosBundleId: 'com.example.loginauthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHmAX1hgdnO911Ya9oj1x3UMXYv9cRiek',
    appId: '1:470866763792:web:5690db215328338a26aa95',
    messagingSenderId: '470866763792',
    projectId: 'authyaksignin',
    authDomain: 'authyaksignin.firebaseapp.com',
    storageBucket: 'authyaksignin.appspot.com',
  );
}
